### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by randomwangran** [d12frosted/vino#82]
Just to say thank you for the inspiration :)

Not only for tracking vino. The user could extend it to anything. 

1. cyclists who are interested in the grand tours can use this to make race tracking
2. cooker can track his recipes
3. bodybuilder can track what kinda exercises he interested
4. musician can track different type of song

...

Thank you.

**Comment by d12frosted** [comment]
@randomwangran I am glad to hear that! Thank you for reaching me ❤️ 

Indeed, as I [mentioned in README][1], this approach can be used for many other things. I use it for tea and books. You are giving other interesting use cases. 

So while `vino` repository is focused solely on wine cellar, I try to extract generic code to [vulpea][2] library ('vulpea' stands for 'fox' in Romanian), that I also use outside of `vino` project. My idea was that anyone can build own solutions on top of `vulpea`. And I am going to keep that approach during following milestones, so whatever I do for `vino` can be easily reused by others. 

BTW, I just realised that I didn't enable discussions in this repository, so feel free to start a thread there 😸 

Cheers

  [1]: https://github.com/d12frosted/vino#why-not-generalise
  [2]: https://github.com/d12frosted/vulpea

**Comment by d12frosted** [comment]
Closing this one. Feel free to continue conversation here.
